server:
  port: 8001

#配置Druid数据源
spring:
  application:
    #微服务名称
    name: cloud-payment-service

  #配置Druid数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/alibaba?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiong.entity #所有Entity别类名所在的包


##配置热部署
#devtools:
#  restart:
#    #设置开启热部署
#    enabled: true
#    #设置修改文件后需要重启的目录
eureka:
  client:
    #是否从Eurekaserver抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon 使用负载均衡
    fetch-registry: true
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
#    additional-paths: src/main/java